development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DBNAME'] %>
  pool: 100
  host: <%= ENV['DTLDBHOST'] %>
  username: <%= ENV['DTLDBUSER'] %>
  password: <%= ENV['DTLDBPWD'] %>
