development:
  adapter: postgresql
  encoding: unicode
  database: db-dtl_development
  pool: 5
  host: <%= ENV['DTLDBHOST'] %>
  username: <%= ENV['DTLDBUSER'] %>
  password: <%= ENV['DTLDBPWD'] %>  